name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto back code format
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "kanjeng-userbot"
          replace: "kanjeng-userbot"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'SeD Replacer'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: AftahBagas
          commit_user_email: aftahbagas21@gmail.com
          commit_author: AftahBagas <aftahbagas21@gmail.com>
